{
  "headers": {
    "x-source-system": "localhost",
    "x-correlation-id": "84d76ab2-2e9a-432a-b297-a9c5bb37b37c",
    "x-idempotency-key": "67cf6f17-3a61-4b67-8e17-1a973d5fc3c6",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.37.3",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "c0834991-4e69-43fe-9504-bf3b8c066ac0",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "217"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/customers",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/customers",
  "listenerPath": "/api/*",
  "relativePath": "/api/customers",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/customers",
  "rawRequestPath": "/api/customers",
  "remoteAddress": "/127.0.0.1:63393",
  "requestPath": "/api/customers"
}